export class MockCagriList {

    constructor() {
    }

    cagriList =
        [{
            "randevuTarihi": "2016-09-23 16:00:00.0",
            "cagriTarihi": "2016-09-23 14:57:11.0",
            "hizmetTipi": "008",
            "hizmetTipiAdi": "Ilk Çalistirma",
            "mamAnaGrp": "UA001",
            "mamAnaGrpAdi": null,
            "basvuruNedeni": "004",
            "basvuruNedenAdi": null,
            "seqNo": "4463722",
            "durum": "ACIK",
            "cmTarihi": null,
            "cmNo": null,
            "musId": "4692956",
            "musKod": "246",
            "adi": "YUSUF GÖKHAN",
            "soyadi": "YAVUZ",
            "firmaUnvani": null,
            "musTip": "B",
            "evTel": null,
            "isTel": null,
            "gsmNo": "5059112099",
            "eposta": "YUSUF.YAVUZ@sistek.com.tr",
            "sehirKod": "34",
            "sehir": "ISTANBUL",
            "ilceKod": "3417",
            "ilce": "ESENLER",
            "semt": null,
            "mahalle": "MENDERES",
            "cadde": null,
            "sokak": "324",
            "aparman": null,
            "apartmanNo": "5",
            "blok": null,
            "daireNo": "4",
            "mamKod": "8006908100",
            "mamAdi": "PROTEUS KOMBI 23.3HM DG",
            "mamSeriNo": "123456789001",
            "mamSeriNo2": null,
            "sattar": "2016-09-01 00:00:00.0",
            "garanti": "VAR",
            "mesguliyet": "YOK",
            "nobet": "YOK",
            "anket": {
                "anketMst": null,
                "anketSorular": null,
                "anketCevaplar": null
            },
            "serKod": "ECA_TEST",
            "serAdi": "ECA TEST",
            "bayiKod": null,
            "ikKod": "5961",
            "kapatmaKodu": null,
            "cozumKodu": null,
            "aciklama": null,
            "servisNotu": null,
            "merkezNotu": null,
            "odemeTipi": null,
            "iletisimIstek": null,
            "detayDtoList": [
                [{
                    "seqNo": "4463722",
                    "satirNo": "1",
                    "islemKod": "00001",
                    "arizaKod": "00001",
                    "mlzIsc": "MLZ",
                    "mlzIscKod": "AG1",
                    "aciklama": "ARTI GARANTİ (1 YIL) KOMBİ",
                    "miktar": "1.0",
                    "birimFiyat": "152.54",
                    "tutar": "152.54",
                    "garFiyat": "0.0",
                    "garTutar": "0.0",
                    "olcuBrm": "AD",
                    "satirHata": null,
                    "kdvOran": "18.0"
                }, {
                    "seqNo": "4463722",
                    "satirNo": "2",
                    "islemKod": "00001",
                    "arizaKod": "00001",
                    "mlzIsc": "ISC",
                    "mlzIscKod": "090435",
                    "aciklama": "VALF MOTORU DEGISIMI",
                    "miktar": "1.0",
                    "birimFiyat": "14.28",
                    "tutar": "14.28",
                    "garFiyat": "0.0",
                    "garTutar": "0.0",
                    "olcuBrm": "AD",
                    "satirHata": null,
                    "kdvOran": "18.0"
                }]
            ],
            "islemList": [
                [{
                    "islSira": "1",
                    "seqNo": "4463722",
                    "basTar": "2016-11-16 11:56:00.0",
                    "bitTar": "2017-10-24 13:33:00.0",
                    "durum": "BITIR",
                    "bekleKaynak": null,
                    "beklemeNeden": null
                }]
            ],
            "islemTarihi": "2016-11-16 11:56:00.0",
            "islemBitTarihi": "2017-10-24 13:33:00.0"
        }, {
            "randevuTarihi": "2016-12-28 15:00:00.0",
            "cagriTarihi": "2017-10-24 13:12:37.0",
            "hizmetTipi": "008",
            "hizmetTipiAdi": "Ilk Çalistirma",
            "mamAnaGrp": "UA001",
            "mamAnaGrpAdi": null,
            "basvuruNedeni": "004",
            "basvuruNedenAdi": null,
            "seqNo": "4463880",
            "durum": "ACIK",
            "cmTarihi": "2016-12-28 10:07:00.0",
            "cmNo": "201612944221",
            "musId": "4735981",
            "musKod": "255",
            "adi": "BİLGİ",
            "soyadi": "TALEBİ",
            "firmaUnvani": null,
            "musTip": "B",
            "evTel": null,
            "isTel": null,
            "gsmNo": "5311111111",
            "eposta": null,
            "sehirKod": "34",
            "sehir": "ISTANBUL",
            "ilceKod": "3430",
            "ilce": "SARIYER",
            "semt": "-",
            "mahalle": "Emirgan",
            "cadde": "-",
            "sokak": "-",
            "aparman": "-",
            "apartmanNo": "-",
            "blok": "-",
            "daireNo": "-",
            "mamKod": "8006908000",
            "mamAdi": "PROTEUS KOMBI 23.3HM DG",
            "mamSeriNo": "2152450000",
            "mamSeriNo2": null,
            "sattar": "2009-10-01 00:00:00.0",
            "garanti": "YOK",
            "mesguliyet": "YOK",
            "nobet": "YOK",
            "anket": {
                "anketMst": null,
                "anketSorular": null,
                "anketCevaplar": null
            },
            "serKod": "ECA_TEST",
            "serAdi": "ECA TEST",
            "bayiKod": null,
            "ikKod": "5961",
            "kapatmaKodu": null,
            "cozumKodu": null,
            "aciklama": "SORUN GİDERİLDİ.",
            "servisNotu": null,
            "merkezNotu": null,
            "odemeTipi": null,
            "iletisimIstek": null,
            "detayDtoList": [],
            "islemList": [
                [{
                    "islSira": "1",
                    "seqNo": "4463880",
                    "basTar": "2017-10-24 00:00:00.0",
                    "bitTar": null,
                    "durum": "BASLA",
                    "bekleKaynak": null,
                    "beklemeNeden": null
                }]
            ],
            "islemTarihi": "2017-10-24 00:00:00.0",
            "islemBitTarihi": null
        }, {
            "randevuTarihi": "2017-09-11 18:00:00.0",
            "cagriTarihi": "2017-09-11 12:18:52.0",
            "hizmetTipi": "012",
            "hizmetTipiAdi": "Mamul Degisimi",
            "mamAnaGrp": "UA001",
            "mamAnaGrpAdi": null,
            "basvuruNedeni": "DIGER",
            "basvuruNedenAdi": null,
            "seqNo": "4463868",
            "durum": "ACIK",
            "cmTarihi": null,
            "cmNo": null,
            "musId": "3424411",
            "musKod": "201",
            "adi": "DENEME",
            "soyadi": "DENEME",
            "firmaUnvani": null,
            "musTip": "B",
            "evTel": "2122585857",
            "isTel": null,
            "gsmNo": null,
            "eposta": null,
            "sehirKod": "34",
            "sehir": "ISTANBUL",
            "ilceKod": "3403",
            "ilce": "ATAŞEHİR",
            "semt": "D",
            "mahalle": "D",
            "cadde": "C",
            "sokak": "D",
            "aparman": "D",
            "apartmanNo": "D",
            "blok": "D",
            "daireNo": "D",
            "mamKod": "8006908000",
            "mamAdi": "PROTEUS KOMBI 23.3HM DG",
            "mamSeriNo": "Kyckyciyciyckh",
            "mamSeriNo2": null,
            "sattar": "2015-08-30 00:00:00.0",
            "garanti": "YOK",
            "mesguliyet": "YOK",
            "nobet": "YOK",
            "anket": {
                "anketMst": null,
                "anketSorular": null,
                "anketCevaplar": null
            },
            "serKod": "ECA_TEST",
            "serAdi": "ECA TEST",
            "bayiKod": null,
            "ikKod": "5961",
            "kapatmaKodu": "NORMAL",
            "cozumKodu": "013",
            "aciklama": "açıklama",
            "servisNotu": null,
            "merkezNotu": null,
            "odemeTipi": "NAKIT",
            "iletisimIstek": null,
            "detayDtoList": [
                [{
                    "seqNo": "4463868",
                    "satirNo": "0",
                    "islemKod": "00001",
                    "arizaKod": "00001",
                    "mlzIsc": "ISC",
                    "mlzIscKod": "090435",
                    "aciklama": "VALF MOTORU DEGISIMI",
                    "miktar": "1.0",
                    "birimFiyat": "29.66",
                    "tutar": "29.66",
                    "garFiyat": "0.0",
                    "garTutar": "0.0",
                    "olcuBrm": "AD",
                    "satirHata": null,
                    "kdvOran": "18.0"
                }, {
                    "seqNo": "4463868",
                    "satirNo": "1",
                    "islemKod": "00001",
                    "arizaKod": "00001",
                    "mlzIsc": "MLZ",
                    "mlzIscKod": "410824033",
                    "aciklama": "YATAK, ARA KESME VALFI",
                    "miktar": "1.0",
                    "birimFiyat": "0.5",
                    "tutar": "0.5",
                    "garFiyat": "0.0",
                    "garTutar": "0.0",
                    "olcuBrm": "AD",
                    "satirHata": null,
                    "kdvOran": "18.0"
                }]
            ],
            "islemList": [
                [{
                    "islSira": "1",
                    "seqNo": "4463868",
                    "basTar": "2017-09-28 09:32:00.0",
                    "bitTar": "2017-12-04 14:24:00.0",
                    "durum": "BITIR",
                    "bekleKaynak": null,
                    "beklemeNeden": null
                }]
            ],
            "islemTarihi": "2017-09-28 09:32:00.0",
            "islemBitTarihi": "2017-12-04 14:24:30.0"
        }]
}