/**
 * @author malisahin
 * @date 2018-04-08
 */

export class Constants {
  constructor() {

  }

  public static API_PAGE_SIZE = 10000;

  public static STATUS = {
    SUCCESS: "SUCCESS",
    ERROR: "ERROR"
  };

  public static URUN_ANA_GRUP_TYPE = {
    ANA_GRUP_LISTE: "ANA_GRUP_LISTE",
    BASVURU_LISTE: "BASVURU_LISTE",
    COZUM_LISTE: "COZUM_LISTE"
  };

  public static TABLE_NAME = {
    URUN: "OFF_MAM_TNM",
    URUN_ANA_GRUP: "OFF_MAM_ANAGRP_TNM",
    URUN_ISCILIK: "OFF_MAM_ISC_TNM",
    URUN_MALZEME: "OFF_MAM_ISC_TNM",
    SEHIR_TNM: "SEHIR_TNM",
    ILCE_TNM: "ILCE_TNM",
    MAHALLE_TNM: "MAHALLE_TNM",
    FIYAT: "OFF_FIYAT",
    ISLEM_ARIZA_ISCILIK: "OFF_ISC_ISLARZGRP_TNM"
  };

  public static SEARCH_TYPE = {LIKE: "LIKE", EXACT: "EXACT"};

  public static DATA_TYPE = {
    URUN: "URUN",
    URUN_ANA_GRUP: "URUN_ANA_GRUP",
    URUN_ISCILIK: "URUN_ISCILIK",
    URUN_MALZEME: "URUN_MALZEME",
    SEHIR_TNM: "SEHIR_TNM",
    ILCE_TNM: "ILCE_TNM",
    MAHALLE_TNM: "MAHALLE_TNM",
    ISCILIK_FIYAT: "ISCILIK_FIYAT",
    MALZEME_FIYAT: "MALZEME_FIYAT",
    ISLEM_ARIZA_ISCILIK: "ISLEM_ARIZA_ISCILIK"
  };

  public static GELEN_VERI = {
    GELEN_URUN: "GELEN_URUN",
    GELEN_URUN_ANA_GRUP: "GELEN_URUN_ANA_GRUP",
    GELEN_URUN_ISCILIK: "GELEN_URUN_ISCILIK",
    GELEN_URUN_MALZEME: "GELEN_URUN_MALZEME",
    GELEN_ISLEM_ARIZA_ISCILIK: "GELEN_ISLEM_ARIZA_ISCILIK",
    GELEN_MALZEME_FIYAT: "GELEN_MALZEME_FIYAT",
    GELEN_ISCILIK_FIYAT: "GELEN_ISCILIK_FIYAT",
    GELEN_SEHIR_TNM: "GELEN_SEHIR_TNM",
    GELEN_ILCE_TNM: "GELEN_ILCE_TNM",
    GELEN_MAHALLE_TNM: "GELEN_MAHALLE_TNM"
  };

  public static VERSIYON = {

    CLIENT: {
      URUN: "URUN_CLIENT_VERSIYON",
      URUN_ANA_GRUP: "URUN_ANA_GRUP_CLIENT_VERSIYON",
      URUN_ISCILIK: "URUN_ISCILIK_CLIENT_VERSIYON",
      URUN_MALZEME: "URUN_MALZEME_CLIENT_VERSIYON",
      ISLEM_ARIZA_ISCILIK: "ISLEM_ARIZA_ISCILIK_CLIENT_VERSIYON",
      MALZEME_FIYAT: "MALZEME_FIYAT_CLIENT_VERSIYON",
      ISCILIK_FIYAT: "ISCILIK_FIYAT_CLIENT_VERSIYON",
      SEHIR_TNM: "SEHIR_TNM_CLIENT_VERSIYON",
      ILCE_TNM: "ILCE_TNM_CLIENT_VERSIYON",
      MAHALLE_TNM: "MAHALLE_TNM_CLIENT_VERSIYON"
    },
    SERVER: {

      URUN: "URUN_SERVER_VERSIYON",
      URUN_ANA_GRUP: "URUN_ANA_GRUP_SERVER_VERSIYON",
      URUN_ISCILIK: "URUN_ISCILIK_SERVER_VERSIYON",
      URUN_MALZEME: "URUN_MALZEME_SERVER_VERSIYON",
      ISLEM_ARIZA_ISCILIK: "ISLEM_ARIZA_ISCILIK_SERVER_VERSIYON",
      MALZEME_FIYAT: "MALZEME_FIYAT_SERVER_VERSIYON",
      ISCILIK_FIYAT: "ISCILIK_FIYAT_SERVER_VERSIYON",
      SEHIR_TNM: "SEHIR_TNM_SERVER_VERSIYON",
      ILCE_TNM: "ILCE_TNM_SERVER_VERSIYON",
      MAHALLE_TNM: "MAHALLE_TNM_SERVER_VERSIYON",
    }

  };
  public static COLORS = {
    URUN: "",
    URUN_ANA_GRUP: "",
    URUN_ISCILIK: "",
    URUN_MALZEME: "",
    ISLEM_ARIZA_ISCILIK: "",
    MALZEME_FIYAT: "",
    ISCILIK_FIYAT: "",
    SEHIR_TNM: "",
    ILCE_TNM: "",
    MAHALLE_TNM: ""
  };

  public static ICONS = {
    URUN: "",
    URUN_ANA_GRUP: "",
    URUN_ISCILIK: "",
    URUN_MALZEME: "",
    ISLEM_ARIZA_ISCILIK: "",
    MALZEME_FIYAT: "",
    ISCILIK_FIYAT: "",
    SEHIR_TNM: "",
    ILCE_TNM: "",
    MAHALLE_TNM: ""
  }
}


