
export enum ETable {
    OFF_HIZ_MST,
    OFF_VERSIYON_TAKIP,
    OFF_MAM_TNM,
    OFF_MAM_ISC_TNM,
    OFF_MAM_MLZ_TNM,
    OFF_ISC_ISLARZGRP_TNM,
    OFF_BASVURU_NEDEN_TNM,
    OFF_TESTO_VALUES,
    SEHIR_TNM,
    ILCE_TNM,
    MAHALLE_TNM

}