export enum ETable {
  SER_MAM_ANAGRP_TNM = 'SER_MAM_ANAGRP_TNM',
  SER_MAM_TNM = 'SER_MAM_TNM',
  SER_ISC_ISLARZGRP_TNM = 'SER_ISC_ISLARZGRP_TNM',
  SER_MAM_ISC_TNM = 'SER_MAM_ISC_TNM',
  SER_MAM_MLZ_TNM = 'SER_MAM_MLZ_TNM',
  OFFLINE_ISC_FIYAT = 'OFFLINE_ISC_FIYAT',
  OFFLINE_MLZ_FIYAT = 'OFFLINE_MLZ_FIYAT'

}
